In [2]:
import numpy as np




In [16]:
np.random.seed(100)
print(np.random.permutation(10))
np.random.seed(100)
print(np.random.permutation(10))
np.random.seed(10)
print(np.random.permutation(10))


[7 6 1 5 4 2 0 3 9 8]
[7 6 1 5 4 2 0 3 9 8]
[8 2 5 6 3 1 0 7 4 9]


In [5]:
np.random.permutation(10)


array([5, 3, 4, 7, 6, 8, 9, 2, 1, 0])

In [6]:
np.random.permutation(10)


array([1, 6, 2, 5, 7, 8, 9, 0, 3, 4])

In [7]:
np.random.permutation(10)

array([0, 7, 5, 2, 3, 9, 6, 4, 8, 1])

In [11]:
np.random.rand(4)

array([ 0.03061665,  0.87761494,  0.72743551,  0.54088093])

In [12]:
np.random.rand(4)


array([ 0.13145815,  0.41366737,  0.77872881,  0.58390137])

In [13]:
np.random.rand(4)

array([ 0.18263144,  0.82608225,  0.10540183,  0.28357668])